site_name: OWID data pipeline

repo_name: owid/etl
repo_url: https://github.com/owid/etl

nav:
  - Home: "index.md"
  - Getting started: "getting-started/index.md"
  - Architecture:
      - Overview: "architecture/index.md"
      - Common format: "architecture/common-format.md"
      - Harmonization: "architecture/harmonization.md"
  - Adding data: "adding-data/index.md"
  - API: "api/index.ipynb"
  - Contributing: "contributing/index.md"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - mkdocs-jupyter:
      ignore_h1_titles: True

extra_css:
  - css/extra.css
